### ISSUE TITLE
Using without default styling

### ISSUE THREAD

**Issue by jonathanprehn** [indexiatech/ember-idx-tabs#14]
How can I use ember-idx-tabs without the default styling?

I'm finding myself having to overwrite most of the default styling.

**Comment by lolmaus** [comment]
While you're waiting for an authoritative answer, have a look at this file:

https://github.com/indexiatech/ember-idx-tabs/blob/master/app/initializers/idx-tabs.js

Maybe you can prevent default styles from applying by fiddling with this config. Also see the Styles page of the demo app.

**Comment by asaf** [comment]
Exactly. =)
