### ISSUE TITLE
MissingHelper - Cannot read property 'view' of undefined

### ISSUE THREAD

**Issue by RyanHirsch** [indexiatech/ember-idx-tabs#2]
When I try to use the component from NPM or if I clone this repo and follow the collaboration instructions, I get the following error on any page that contains the component:

```
 Uncaught TypeError: Cannot read property 'view' of undefined
```

Its being thrown within the function `helperMissingHelper(path)` of vendor.js

**Comment by pzuraq** [comment]
The "ember-addon" keyword was missing from the package.json, which means Ember-CLI wasn't able to detect the addon and include it automatically. I opened up a pull-request to solve this issue, but until then you can just add this to the package.json in `node_modules`:

```
"keywords": [
  "ember-addon"
]
```

**Comment by RyanHirsch** [comment]
I don't think this got republished on NPM
