### ISSUE TITLE
Rails Assets component error

### ISSUE THREAD

**Issue by dreikanter** [indexiatech/ember-idx-tabs#5]
I'm trying to add this package in my Rails application, using Rails Assets (https://rails-assets.org), but there is an error during component import similar to this one https://github.com/rails-assets/rails-assets/issues/105

The problem is the lack of version tag. Could you please create a tag with current revision of the package using [semver](http://semver.org) format? It could be 0.0.1, or anything you suggest.

Here is the component import page to check it working: https://rails-assets.org/components/new

**Comment by asaf** [comment]
Done for 0.1.1
