### ISSUE TITLE
ember-idx-tabs and ember-idx-accordion is broken

### ISSUE THREAD

**Issue by jcaffey** [indexiatech/ember-idx-tabs#7]
I'm using ember-cli 0.1.3. If you installed idx-tabs a few days ago everything worked fine. Not sure what happened. Maybe idx-utils is broken now?

I get 'undefined' is not a function from initializers/idx-tabs.js. It complains when attempting to .getConfig. (I think that's the function... sorry, don't have time ATM to look any further.) This also happens in idx-accordion.

I will post something more detailed if you can't reproduce from npm install --save-dev ember-idx-tabs with a fresh ember-cli project.

**Comment by asaf** [comment]
@jcaffey I know, I'm working on fixing the configuration across all projects.

thanks.

**Comment by mkoczka** [comment]
Still problem in ember-cli 0.1.11.

File: app/initializers/idx-tabs
Cannot reassign imported binding `Config`

**Comment by jmimi** [comment]
Is there any temporary solution?

**Comment by ianhoolihan** [comment]
Hi @jcaffey, thanks for the great work. With all respect, do you have a rough ETA for an expected fix or temporary solution?

**Comment by jmimi** [comment]
@ianhoolihan there is a pull request fixes this problem. And that is not merged yet

**Comment by asaf** [comment]
The reason is that we dont like the current way of the config implementation,

We'll try to come up with something very soon.

**Comment by ianhoolihan** [comment]
Awesome, thanks @jmini and @asaf!
